name: base
channels:
- conda-forge
- huggingface
- pytorch
- nvidia
dependencies:
- python=3.10
- pandas
- numpy
- matplotlib
- jupyter
- jupyterlab
- tensorflow
- tensorflow-datasets
- tensorboard
- pytorch
- torchvision
- torchaudio
- pytorch-cuda=11.8
- networkx
- gymnasium
- jax
- jaxlib
- flax
- seaborn
- scikit-learn
- xgboost
- huggingface_hub
- transformers
- tokenizers
- datasets
- safetensors
- accelerate
- spacy
- tqdm
- stable-baselines3