'on':
  github:
    branches:
      only: main
jobs:
  CloneRepo:
    uses: git-checkout@v1  # clone repo action
    with:
      url: context.event.github.url  # see below for where this pionts to
    outputs:
      repo:
        type: volume
    resources:
      instance-type: C5
  LeNet_HW1:
    uses: create-model@v1
    with:
      model: hw1/lenet.keras
      model-name: lenet-mnist
      modelVersion: latest
      type: Tensorflow
    resources:
      instance-type: C5
context:
  event:
    github:
      ref: c0504e8e6ba54e7fe15217c91c3eac5e05603860
      url: https://github.com/AmeerArsala/CSC-587  # context.event.github.url
