# On push to github repository, do all this with gradient
'on':
  github:
    branches:
      only: main

defaults:
  env:
    apiKey: secret:GRADIENT_API_KEY

jobs:
  CloneRepo:
    uses: git-checkout@v1  # clone repo action
    with:
      url: context.event.github.url  # see below for where this points to
    outputs:
      repo:
        type: volume
    resources:
      instance-type: C5
  
  GatherModels:
    uses: script@v1
    with:
      # For each of these, put `cp -R source dest` to copy from the inputs repo -> outputs dir
      image: bash:latest
      script: |-
        echo "Hello World!"
        cd /inputs/repo
        cp -R hw1/models/* /outputs/hw1_lenet
    inputs:
      repo: CloneRepo.outputs.repo
    #outputs:
    #  models:
    #    lenet:
    #      type: dataset
    #      with:
    #        ref: lenet-mnist
    needs:
      - CloneRepo
    resources:
      instance-type: C5
    
context:
  event:
    github:
      ref: c0504e8e6ba54e7fe15217c91c3eac5e05603860
      url: https://github.com/AmeerArsala/CSC-587  # context.event.github.url
