# On push to github repository, do all this with gradient
'on':
  github:
    branches:
      only: main
jobs:
  CloneRepo:
    uses: git-checkout@v1  # clone repo action
    with:
      url: context.event.github.url  # see below for where this points to
    outputs:
      repo:
        type: volume
    resources:
      instance-type: C5
  


context:
  event:
    github:
      ref: c0504e8e6ba54e7fe15217c91c3eac5e05603860
      url: https://github.com/AmeerArsala/CSC-587  # context.event.github.url
